PIPELINE_SWITCH:
  PIPELINE_TEST: False
FEATURE_SET_VARS: 
  IMPUTATION: 'Linear'
  MIN_THRESHOLD: 5
FOLDERS:
  DATA: 'data'
  RAW_FEATURESET: 'raw_featureset'
  TEMPORAL: 'temporal_data'
  POST_PROCESSED_FEATURESET: 'post_processed_featureset'
FEATURE_SET:
  RAW_FEATURESET_EXCEL: 'Datos.xlsx'
  SPLIT_LABEL_NAME: 'HeartDisease'
  FEATURESET_EXCEL: 'Data_featureset.xlsx'
  LABELS_EXCEL: 'Data_labelset.xlsx'
  FEATURES_TRAIN: 'Train_featureset.xlsx'
  FEATURES_TEST: 'Test_featureset.xlsx'
  LABELS_TRAIN: 'Train_labelset.xlsx'
  LABELS_TEST: 'Test_labelset.xlsx'
  POST_PROCESSED_EXCEL: 'Post_processed_featureset.xlsx'
  POSTPROCESSING_STEPS:
    STANDARDIZATION: False
    NORMALIZATION: True
    ONE_HOT_ENCODING: True